version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: reactnative-app-container
    ports:
      - '8081:8081'
    volumes:
      - ./frontend:/usr/src/app
    # command: ['npx', 'expo', 'start', '--tunnel']
    command: tail -f /dev/null

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: nestjs-app-container
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/sportSchedule
      - DATABASE_NAME=sportSchedule
      - DATABASE_USER=
      - DATABASE_PASS=
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
    command: tail -f /dev/null
    # command: ['npm', 'run', 'start:backend']
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo-container
    # ports:
    #   - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
