version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '8081:8081'
    volumes:
      - ./frontend:/usr/src/app
    command: ['npx', 'react-native', 'start', '--terminal', 'bash']

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
    command: ['npm', 'run', 'start:backend']
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

