version: '3.7'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '8081:8081'
  db:
    image: mongo
    ports:
      - '27017:27017'
