export const LeaguesEnum: Record<string, string> = {
  'MLB': 'MLB',
  'MLS': 'MLS',
  'NBA': 'NBA',
  'NCAAB': 'NCAAB',
  'NCAAF': 'NCAAF',
  'NCAAMH': 'NCAAMH',
  'NCAAWH': 'NCAAWH',
  'NCCABB': 'NCCABB',
  'NFL': 'NFL',
  'NHL': 'NHL',
  'NWSL': 'NWSL',
  'OLYMPICS-MEN': 'OLYMPICS-MEN',
  'OLYMPICS-WOMEN': 'OLYMPICS-WOMEN',
  'PWHL': 'PWHL',
  'WNBA': 'WNBA',
  'WNCAAB': 'WNCAAB',
};
