import { maxFavoritesNumber } from '@/constants/Constants';
import { saveCache } from '@/utils/fetchData';
import { doc, serverTimestamp, setDoc } from 'firebase/firestore';
import { auth, db } from './firebaseConfig';
import { Team } from './types';

export const randomNumber = (max) => {
  return Math.floor(Math.random() * (max - 0 + 1) + 0);
};

export const getRandomTeamId = (teams: Team[]) => {
  return teams[randomNumber(teams.length) - 1]?.uniqueId;
};

export const addNewTeamId = (selection: string[], teams: Team[]) => {
  const randomId = getRandomTeamId(teams);
  if (randomId && !selection.includes(randomId)) {
    selection.push(randomId);
  }
  return selection;
};

export const removeLastTeamId = (selection: string[]) => {
  selection.pop();
  return selection;
};

export const addFavoriteTeam = async (favoriteTeams: string[], teamId: string) => {
  const isIncluded = favoriteTeams.includes(teamId);
  let updatedFavorites = [...favoriteTeams];

  if (isIncluded && favoriteTeams.length > 1) {
    // Only remove team if at least one remains after
    updatedFavorites = favoriteTeams.filter((id) => id !== teamId);
    saveCache('favoriteTeams', updatedFavorites);
  } else if (!isIncluded && favoriteTeams.length < maxFavoritesNumber) {
    updatedFavorites = [...favoriteTeams, teamId];
    saveCache('favoriteTeams', updatedFavorites);
  }

  const currentUser = auth.currentUser;
  if (currentUser) {
    try {
      const userRef = doc(db, 'users', currentUser.uid);
      await setDoc(
        userRef,
        {
          favoriteTeams: updatedFavorites,
          lastUpdate: serverTimestamp(),
        },
        { merge: true },
      );
    } catch (e: unknown) {
      console.error('Error syncing favorite team to Firestore:', e);
    }
  }

  if (globalThis.window !== undefined) {
    globalThis.window.dispatchEvent(new Event('favoritesUpdated'));
  }
};

interface ICSFileParams {
  homeTeam: string;
  awayTeam: string;
  startTimeUTC: string;
  arenaName: string;
  placeName: string;
}

const formatICSDate = (date: Date): string => {
  return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
};

export const generateICSFile = ({ homeTeam, awayTeam, startTimeUTC, arenaName, placeName }: ICSFileParams) => {
  const startDate = new Date(startTimeUTC);

  if (isNaN(startDate.getTime())) {
    console.error('Invalid startTimeUTC provided:', startTimeUTC);

    return;
  }

  const endDate = new Date(startDate.getTime() + 3 * 60 * 60 * 1000);
  const now = new Date();

  const eventUID = `${formatICSDate(startDate)}`;

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'BEGIN:VEVENT',
    `UID:${eventUID}`,
    `DTSTAMP:${formatICSDate(now)}`,
    `DTSTART:${formatICSDate(startDate)}`,
    `DTEND:${formatICSDate(endDate)}`,
    `SUMMARY:${homeTeam} vs ${awayTeam}`,
    `LOCATION:${arenaName}, ${placeName}`,
    `DESCRIPTION:Game between ${homeTeam} and ${awayTeam} at ${arenaName}`,
    'TRANSP:OPAQUE',
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');

  try {
    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    // Sanitize filename slightly
    const filename = `${homeTeam}_vs_${awayTeam}.ics`.replace(/[^a-z0-9_.-]/gi, '_');
    link.download = filename;
    link.click();

    setTimeout(() => URL.revokeObjectURL(url), 100);
  } catch (e: unknown) {
    console.error('Error generating or downloading ICS file:', e);
    return;
  }
};

export const translateFilterLabel = (context: 'league' | 'team' | 'date') => {
  const language = (typeof navigator !== 'undefined' ? navigator.language : 'en').split('-')[0];

  switch (language) {
    case 'fr':
      return context === 'league'
        ? 'Filtrer par ligue'
        : context === 'team'
          ? 'Filtrer par équipe'
          : 'Filtrer par date';
    case 'de':
      return context === 'league'
        ? 'Nach Liga filtern'
        : context === 'team'
          ? 'Nach Team filtern'
          : 'Nach Datum filtern';
    case 'es':
      return context === 'league'
        ? 'Filtrar por liga'
        : context === 'team'
          ? 'Filtrar por equipo'
          : 'Filtrar por fecha';
    case 'it':
      return context === 'league' ? 'Filtra per lega' : context === 'team' ? 'Filtra per squadra' : 'Filtra per data';
    case 'ja':
      return context === 'league' ? 'リーグで絞り込む' : context === 'team' ? 'チームで絞り込む' : '日付で絞り込む';
    case 'ko':
      return context === 'league' ? '리그로 필터링' : context === 'team' ? '팀으로 필터링' : '날짜로 필터링';
    case 'nl':
      return context === 'league' ? 'Filter op competitie' : context === 'team' ? 'Filter op team' : 'Filter op datum';
    case 'pt':
      return context === 'league' ? 'Filtrar por liga' : context === 'team' ? 'Filtrar por time' : 'Filtrar por data';
    case 'ru':
      return context === 'league' ? 'Фильтр по лиге' : context === 'team' ? 'Фильтр по команде' : 'Фильтр по дате';
    case 'zh':
      return context === 'league' ? '按联赛筛选' : context === 'team' ? '按球队筛选' : '按日期筛选';
    default:
      return context === 'league' ? 'Filter by league' : context === 'team' ? 'Filter by team' : 'Filter by date';
  }
};

export const translateWord = (word: string) => {
  let translation: { [key: string]: string } = {};
  const language = navigator.language.split('-')[0];
  switch (language) {
    case 'fr':
      translation = {
        all: 'TOUS',
        gamesOfDay: 'Programme du jour',
        remainingGames: 'Matchs restants',
        focusTeam: 'Suivre une équipe',
        calendars: 'Agenda',
        connection: 'Connexion',
        noResults: 'Pas de résultats',
        inProgress: 'En cours',
        noOptionsAvailable: 'Aucune option disponible',
        wrongPage: "Cette page n'existe pas.",
        homeScreen: "Aller à la page d'accueil!",
        selectAll: 'Tout sélectionner',
        Filter: 'Filtrer',
        ended: 'Terminé',
        yourFav: 'Vos équipes favorites',
        register: 'Sauvegarder',
        cancel: 'Annuler',
        deleteSelection: 'Supprimer la sélection',
        addColumn: 'Ajouter une colonne',
        removeColumn: 'Supprimer une colonne',
        select: 'Faites votre choix',
        selectMultiple: 'Sélectionnez vos choix',
        nothing: 'Aucun',
        filterTeams: 'Filtrer les équipes',
        filterLeagues: 'Filtrer les ligues',
        filterMonths: 'Filtrer les mois',
        findTeam: 'Trouver une équipe',
        leagueSurveilled: 'Ligue(s) à afficher',
        score: 'Résultat final',
        favorites: 'FAVORIS',
        followLive: 'Suivre le direct',
        scoreView: 'Afficher les scores',
        localizeArena: "Localiser l'arène",
        downloadICS: 'Fichier .ics',
        gameDetails: 'Détails du match',
        events: 'Evenements',
        final: 'Finalisation',
        standings: 'Classement',
        currentScore: 'Score actuel',
        showHidePreviousScores: 'Afficher/Masquer les scores précédents',
        postponedGame: 'Match reporté',
        signInWithGoogle: 'Se connecter avec Google',
        signOut: 'Se déconnecter',
        authentication: 'Identifiez vous',
        continueWithEmail: 'Inscrivez-vous / Connectez-vous',
        forgotPassword: 'Mot de passe oublié ?',
        loggedInAs: 'Vous êtes connecté avec :',
        passwordResetSent: 'Un lien de réinitialisation de mot de passe a été envoyé à votre adresse e-mail !',
        incorrectPassword: 'Mot de passe incorrect pour ce compte. Veuillez réessayer.',
        authError: "Erreur d'authentification : ",
        loginError: 'Erreur de connexion : ',
        enterEmailFirst: 'Veuillez d’abord saisir votre adresse e-mail.',
        resetError: 'Erreur de réinitialisation : ',
        connectionError: 'Erreur de connexion : ',
        noUserLoggedIn: 'Aucun utilisateur connecté.',
        confirmDeleteAccount:
          'Êtes-vous sûr de vouloir supprimer définitivement votre compte ? Cette action est irréversible.',
        accountDeleted: 'Votre compte a été supprimé avec succès.',
        recentLoginRequired:
          'Pour des raisons de sécurité, veuillez vous déconnecter puis vous reconnecter avant de supprimer votre compte.',
        deletionError: 'Erreur de suppression : ',
        deleteAccount: 'Supprimer le compte',
        emailPlaceholder: 'Adresse e-mail',
        passwordPlaceholder: 'Mot de passe',
        signIn: 'Connectez-vous',
        signUp: "S'inscrire",
        noAccount: 'Pas encore de compte ?',
        alreadyHaveAccount: 'Déjà un compte ?',
        passwordConfirmPlaceholder: 'Confirmez le mot de passe',
        passwordsDoNotMatch: 'Les mots de passe ne correspondent pas.',
        userNotFound: 'Aucun compte trouvé pour cet e-mail.',
        emailAlreadyInUse: 'Cet e-mail est déjà utilisé par un autre compte.',
        invalidCredentials: 'E-mail ou mot de passe incorrect.',
        or: 'ou',
        profile: 'Mon Profil',
        changePreferences: 'Changer mes préférences',
      };
      break;
    case 'de':
      translation = {
        all: 'alle',
        gamesOfDay: 'Spiele des Tages',
        remainingGames: 'Verbleibende Spiele',
        focusTeam: 'Team verfolgen',
        calendars: 'Agenda',
        connection: 'Verbindung',
        noResults: 'Keine Ergebnisse',
        inProgress: 'In Bearbeitung',
        noOptionsAvailable: 'Keine Optionen verfügbar',
        wrongPage: 'Diese Seite existiert nicht.',
        homeScreen: 'Zur Startseite gehen!',
        selectAll: 'Alle auswählen',
        Filter: 'Filtern',
        ended: 'Beendet',
        yourFav: 'Deine Lieblingsteams',
        register: 'Speichern',
        cancel: 'Abbrechen',
        deleteSelection: 'Auswahl löschen',
        addColumn: 'Spalte hinzufügen',
        removeColumn: 'Spalte entfernen',
        select: 'Wähle deine Auswahl',
        selectMultiple: 'Wählen Sie Ihre Optionen',
        nothing: 'Nichts',
        filterTeams: 'Teams filtern',
        filterLeagues: 'Leagues filtern',
        filterMonths: 'Monate filtern',
        findTeam: 'Ein Team finden',
        leagueSurveilled: 'Anzuzeigende Liga/Ligen',
        score: 'Endstand',
        favorites: 'FAVORITEN',
        followLive: 'Live verfolgen',
        scoreView: 'Spielstände anzeigen',
        localizeArena: 'Arena lokalisieren',
        downloadICS: 'ICS-Datei',
        gameDetails: 'Spieldetails',
        events: 'Ereignisse',
        final: 'Ergebnis',
        standings: 'Standings',
        currentScore: 'Aktueller Spielstand',
        showHidePreviousScores: 'Vorherige Scores anzeigen/verstecken',
        postponedGame: 'Spiel verschoben',
        signInWithGoogle: 'Mit Google anmelden',
        signOut: 'Abmelden',
        authentication: 'Identifizieren Sie sich',
        continueWithEmail: 'Registrieren / Anmelden',
        forgotPassword: 'Passwort vergessen?',
        loggedInAs: 'Angemeldet als:',
        passwordResetSent: 'Ein Link zum Zurücksetzen des Passworts wurde an Ihren Posteingang gesendet!',
        incorrectPassword: 'Falsches Passwort für dieses Konto. Bitte versuchen Sie es erneut.',
        authError: 'Authentifizierungsfehler: ',
        loginError: 'Anmeldefehler: ',
        enterEmailFirst: 'Bitte geben Sie zuerst Ihre E-Mail-Adresse ein.',
        resetError: 'Fehler beim Zurücksetzen: ',
        connectionError: 'Verbindungsfehler: ',
        noUserLoggedIn: 'Kein Benutzer angemeldet.',
        confirmDeleteAccount:
          'Sind Sie sicher, dass Sie Ihr Konto dauerhaft löschen möchten? Dies kann nicht rückgängig gemacht werden.',
        accountDeleted: 'Ihr Konto wurde erfolgreich gelöscht.',
        recentLoginRequired:
          'Aus Sicherheitsgründen melden Sie sich bitte ab und wieder an, bevor Sie Ihr Konto löschen.',
        deletionError: 'Fehler beim Löschen: ',
        deleteAccount: 'Konto löschen',
        emailPlaceholder: 'E-Mail-Adresse',
        passwordPlaceholder: 'Passwort',
        signIn: 'Anmelden',
        signUp: 'Registrieren',
        noAccount: 'Noch kein Konto?',
        alreadyHaveAccount: 'Bereits ein Konto?',
        passwordConfirmPlaceholder: 'Passwort bestätigen',
        passwordsDoNotMatch: 'Passwörter stimmen nicht überein.',
        userNotFound: 'Kein Konto für diese E-Mail gefunden.',
        emailAlreadyInUse: 'Diese E-Mail wird bereits verwendet.',
        invalidCredentials: 'E-Mail oder Passwort falsch.',
        or: 'oder',
        profile: 'Mein Profil',
        changePreferences: 'Präferenzen ändern',
      };
      break;
    case 'es':
      translation = {
        all: 'TODOS',
        gamesOfDay: 'Juegos del día',
        remainingGames: 'Juegos restantes',
        focusTeam: 'Seguir a un equipo',
        calendars: 'Agenda',
        connection: 'Conexión',
        noResults: 'Sin resultados',
        inProgress: 'En progreso',
        noOptionsAvailable: 'No hay opciones disponibles',
        wrongPage: 'Esta página no existe.',
        homeScreen: 'Ir a la pantalla de inicio!',
        selectAll: 'Seleccionar todo',
        Filter: 'Filtrar',
        ended: 'Finalizado',
        yourFav: 'Tus equipos favoritos',
        register: 'Guardar',
        cancel: 'Cancelar',
        deleteSelection: 'Eliminar selección',
        addColumn: 'Añadir columna',
        removeColumn: 'Eliminar columna',
        select: 'Selecciona tu opción',
        selectMultiple: 'Seleccione sus opciones',
        nothing: 'Nada',
        filterTeams: 'Filtrar equipos',
        filterLeagues: 'Filtrar ligas',
        filterMonths: 'Filtrar meses',
        findTeam: 'Encontrar un equipo',
        leagueSurveilled: 'Liga(s) a mostrar',
        score: 'Marcador final',
        favorites: 'FAVORITOS',
        followLive: 'Seguir en vivo',
        scoreView: 'Mostrar marcadores',
        localizeArena: 'Localizar arena',
        downloadICS: 'Archivo .ics',
        gameDetails: 'Detalles del juego',
        events: 'Eventos',
        final: 'Final',
        standings: 'Clasificaciones',
        currentScore: 'Marcador actual',
        showHidePreviousScores: 'Mostrar/Ocultar marcadores anteriores',
        postponedGame: 'Juego pospuesto',
        signInWithGoogle: 'Iniciar sesión con Google',
        signOut: 'Cerrar sesión',
        authentication: 'Identificarse',
        continueWithEmail: 'Registrarse / Iniciar sesión',
        forgotPassword: '¿Has olvidado tu contraseña?',
        loggedInAs: 'Conectado como:',
        passwordResetSent: '¡Se ha enviado un enlace de restablecimiento de contraseña a tu bandeja de entrada!',
        incorrectPassword: 'Contraseña incorrecta para esta cuenta. Por favor, inténtalo de nuevo.',
        authError: 'Error de autenticación: ',
        loginError: 'Error de inicio de sesión: ',
        enterEmailFirst: 'Por favor, introduce primero tu correo electrónico.',
        resetError: 'Error de restablecimiento: ',
        connectionError: 'Error de conexión: ',
        noUserLoggedIn: 'No hay ningún usuario conectado.',
        confirmDeleteAccount:
          '¿Estás seguro de que quieres eliminar permanentemente tu cuenta? Esta acción no se puede deshacer.',
        accountDeleted: 'Tu cuenta ha sido eliminada con éxito.',
        recentLoginRequired:
          'Por razones de seguridad, cierra la sesión y vuelve a iniciarla antes de eliminar tu cuenta.',
        deletionError: 'Error de eliminación: ',
        deleteAccount: 'Eliminar cuenta',
        emailPlaceholder: 'Correo electrónico',
        passwordPlaceholder: 'Contraseña',
        signIn: 'Iniciar sesión',
        signUp: 'Registrarse',
        noAccount: '¿No tienes cuenta?',
        alreadyHaveAccount: '¿Ya tienes cuenta?',
        passwordConfirmPlaceholder: 'Confirmar contraseña',
        passwordsDoNotMatch: 'Las contraseñas no coinciden.',
        userNotFound: 'No se encontró ninguna cuenta para este correo.',
        emailAlreadyInUse: 'Este correo ya está en uso.',
        invalidCredentials: 'Correo o contraseña incorrectos.',
        or: 'o',
        profile: 'Mi Perfil',
        changePreferences: 'Cambiar mis preferencias',
      };
      break;

    case 'it':
      translation = {
        all: 'TUTTI',
        gamesOfDay: 'Giochi del giorno',
        remainingGames: 'Giochi rimanenti',
        focusTeam: 'Segui una squadra',
        calendars: 'Agenda',
        connection: 'Connessione',
        noResults: 'Nessun risultato',
        inProgress: 'In corso',
        noOptionsAvailable: 'Nessuna opzione disponibile',
        wrongPage: 'Questa pagina non esiste.',
        homeScreen: 'Vai alla pagina iniziale!',
        selectAll: 'Seleziona tutto',
        Filter: 'Filtrare',
        ended: 'Terminato',
        yourFav: 'Le tue squadre preferite',
        register: 'Salva',
        cancel: 'Annulla',
        deleteSelection: 'Elimina selezione',
        addColumn: 'Aggiungi colonna',
        removeColumn: 'Rimuovi colonna',
        select: 'Seleziona la tua scelta',
        selectMultiple: 'Seleziona le tue scelte',
        nothing: 'Niente',
        filterTeams: 'Filtrare squadre',
        filterLeagues: 'Filtrare leghe',
        filterMonths: 'Filtrare mesi',
        findTeam: 'Trova una squadra',
        leagueSurveilled: 'Lega/Leghe da visualizzare',
        score: 'Punteggio finale',
        favorites: 'PREFERITI',
        followLive: 'Segui in diretta',
        scoreView: 'Mostra punteggi',
        localizeArena: "Localizza l'arena",
        downloadICS: 'File .ics',
        gameDetails: 'Dettagli del gioco',
        events: 'Eventi',
        final: 'Finale',
        standings: 'Classifica',
        currentScore: 'Punteggio attuale',
        showHidePreviousScores: 'Mostra/Nascondi punteggi precedenti',
        postponedGame: 'Gioco posticipato',
        signInWithGoogle: 'Accedi con Google',
        signOut: 'Esci',
        authentication: 'Identificarsi',
        continueWithEmail: 'Iscriviti / Accedi',
        forgotPassword: 'Password dimenticata?',
        loggedInAs: 'Connesso come:',
        passwordResetSent: 'Un link per il recupero della password è stato inviato alla tua email!',
        incorrectPassword: 'Password errata per questo account. Riprova.',
        authError: 'Errore di autenticazione: ',
        loginError: 'Errore di accesso: ',
        enterEmailFirst: 'Inserisci prima il tuo indirizzo email.',
        resetError: 'Errore di ripristino: ',
        connectionError: 'Errore di connessione: ',
        noUserLoggedIn: 'Nessun utente loggato.',
        confirmDeleteAccount: 'Sei sicuro di voler eliminare definitivamente il tuo account? L’azione è irreversibile.',
        accountDeleted: 'Il tuo account è stato eliminato con successo.',
        recentLoginRequired: 'Per motivi di sicurezza, esci e accedi di nuovo prima di eliminare il tuo account.',
        deletionError: 'Errore di eliminazione: ',
        deleteAccount: 'Elimina account',
        emailPlaceholder: 'Indirizzo email',
        passwordPlaceholder: 'Password',
        signIn: 'Accedi',
        signUp: 'Iscriviti',
        noAccount: 'Non hai un account?',
        alreadyHaveAccount: 'Hai già un account?',
        passwordConfirmPlaceholder: 'Conferma password',
        passwordsDoNotMatch: 'Le password non corrispondono.',
        userNotFound: 'Nessun account trovato per questa email.',
        emailAlreadyInUse: 'Questa email è già in uso.',
        invalidCredentials: 'Email o password errati.',
        or: 'o',
        profile: 'Il mio Profilo',
        changePreferences: 'Cambia le mie preferenze',
      };
      break;
    case 'ja':
      translation = {
        all: 'すべて',
        gamesOfDay: 'その日のゲーム',
        remainingGames: '残りのゲーム',
        focusTeam: 'チームをフォロー',
        calendars: 'アジェンダ',
        connection: '接続',
        noResults: '結果なし',
        inProgress: '進行中',
        noOptionsAvailable: '利用可能なオプションはありません',
        wrongPage: 'このページは存在しません。',
        homeScreen: 'ホーム画面に移動します！',
        selectAll: 'すべて選択',
        Filter: 'フィルター',
        ended: '終了',
        yourFav: 'お気に入りのチーム',
        register: '保存',
        cancel: 'キャンセル',
        deleteSelection: '選択を削除',
        addColumn: '列を追加',
        removeColumn: '列を削除',
        select: 'あなたの選択を選択してください',
        selectMultiple: '複数の選択肢を選択',
        nothing: 'なし',
        filterTeams: 'チームをフィルター',
        filterLeagues: 'リーグをフィルター',
        filterMonths: '月をフィルター',
        findTeam: 'チームを探す',
        leagueSurveilled: '表示するリーグ',
        score: '最終スコア',
        favorites: 'お気に入り',
        followLive: 'ライブをフォロー',
        scoreView: 'スコアを表示',
        localizeArena: 'アリーナの位置を特定',
        downloadICS: 'ICSファイル',
        gameDetails: 'ゲームの詳細',
        events: 'イベント',
        final: '最終',
        standings: 'スタンディング',
        currentScore: '現在のスコア',
        showHidePreviousScores: '前のスコアを表示/非表示',
        postponedGame: '試合が延期されました',
        signInWithGoogle: 'Googleでサインイン',
        signOut: 'サインアウト',
        authentication: '本人確認を行ってください',
        continueWithEmail: '新規登録 / ログイン',
        forgotPassword: 'パスワードをお忘れですか？',
        loggedInAs: 'ログイン：',
        passwordResetSent: 'パスワード再設定用のリンクをメールで送信しました。',
        incorrectPassword: 'パスワードが正しくありません。もう一度お試しください。',
        authError: '認証エラー: ',
        loginError: 'ログインエラー: ',
        enterEmailFirst: 'まずメールアドレスを入力してください。',
        resetError: 'リセットエラー: ',
        connectionError: '接続エラー: ',
        noUserLoggedIn: 'ユーザーがログインしていません。',
        confirmDeleteAccount: 'アカウントを完全に削除してもよろしいですか？この操作は取り消せません。',
        accountDeleted: 'アカウントが正常に削除されました。',
        recentLoginRequired:
          'セキュリティのため、アカウントを削除する前に一度ログアウトしてから再度ログインしてください。',
        deletionError: '削除エラー: ',
        deleteAccount: 'アカウントを削除する',
        emailPlaceholder: 'メールアドレス',
        passwordPlaceholder: 'パスワード',
        signIn: 'ログイン',
        signUp: '新規登録',
        noAccount: 'アカウントをお持ちでない方',
        alreadyHaveAccount: '既にアカウントをお持ちの方',
        passwordConfirmPlaceholder: 'パスワードを再入力',
        passwordsDoNotMatch: 'パスワードが一致しません。',
        userNotFound: 'アカウントが見つかりません。',
        emailAlreadyInUse: 'このメールは既に使用されています。',
        invalidCredentials: 'メールアドレスまたはパスワードが正しくありません。',
        or: 'または',
        profile: 'マイプロフィール',
        changePreferences: '設定を変更する',
      };
      break;
    case 'ko':
      translation = {
        all: '전체',
        gamesOfDay: '그날의 게임',
        remainingGames: '남은 게임',
        focusTeam: '팀 팔로우',
        calendars: '아젠다',
        connection: '연결',
        noResults: '결과 없음',
        inProgress: '진행 중',
        noOptionsAvailable: '사용 가능한 옵션이 없습니다',
        wrongPage: '이 페이지는 존재하지 않습니다.',
        homeScreen: '홈 화면으로 이동하세요!',
        selectAll: '모두 선택',
        Filter: '필터',
        ended: '종료됨',
        yourFav: '좋아하는 팀',
        register: '저장',
        cancel: '취소',
        deleteSelection: '선택 삭제',
        addColumn: '열 추가',
        removeColumn: '열 제거',
        select: '선택하세요',
        selectMultiple: '여러 항목을 선택하세요',
        nothing: '없음',
        filterTeams: '팀 필터링',
        filterLeagues: '리그 필터링',
        filterMonths: '월 필터링',
        findTeam: '팀 찾기',
        leagueSurveilled: '표시할 리그',
        score: '최종 점수',
        favorites: '즐겨찾기',
        followLive: '라이브 팔로우',
        scoreView: '점수 보기',
        localizeArena: '아레나 위치 지정',
        downloadICS: 'ICS 파일',
        gameDetails: '게임 세부 정보',
        events: '이벤트',
        final: '최종',
        standings: '순위',
        currentScore: '현재 점수',
        showHidePreviousScores: '이전 점수 표시/숨기기',
        postponedGame: '경기 연기됨',
        signInWithGoogle: 'Google로 로그인',
        signOut: '로그아웃',
        authentication: '본인 확인',
        continueWithEmail: '가입하기 / 로그인',
        forgotPassword: '비밀번호를 잊으셨나요?',
        loggedInAs: '로그인 계정:',
        passwordResetSent: '비밀번호 재설정 링크가 이메일로 전송되었습니다!',
        incorrectPassword: '이 계정의 비밀번호가 올바르지 않습니다. 다시 시도해 주세요.',
        authError: '인증 오류: ',
        loginError: '로그인 오류: ',
        enterEmailFirst: '먼저 이메일 주소를 입력해 주세요.',
        resetError: '초기화 오류: ',
        connectionError: '연결 오류: ',
        noUserLoggedIn: '로그인된 사용자가 없습니다.',
        confirmDeleteAccount: '계정을 영구적으로 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
        accountDeleted: '계정이 성공적으로 삭제되었습니다.',
        recentLoginRequired: '보안을 위해 계정을 삭제하기 전에 로그아웃 후 다시 로그인해 주세요.',
        deletionError: '삭제 오류: ',
        deleteAccount: '계정 삭제',
        emailPlaceholder: '이메일 주소',
        passwordPlaceholder: '비밀번호',
        signIn: '로그인',
        signUp: '가입하기',
        noAccount: '계정이 없으신가요?',
        alreadyHaveAccount: '이미 계정이 있으신가요?',
        passwordConfirmPlaceholder: '비밀번호 확인',
        passwordsDoNotMatch: '비밀번호가 일치하지 않습니다.',
        userNotFound: '계정을 찾을 수 없습니다.',
        emailAlreadyInUse: '이미 사용 중인 이메일입니다.',
        invalidCredentials: '이메일 또는 비밀번호가 올바르지 않습니다.',
        or: '또는',
        profile: '내 프로필',
        changePreferences: '기본 설정 변경',
      };
      break;
    case 'nl':
      translation = {
        all: 'ALLE',
        gamesOfDay: 'Spelkalender',
        remainingGames: 'Resterende wedstrijden',
        focusTeam: 'Volg een team',
        calendars: 'Agenda',
        connection: 'Verbinding',
        noResults: 'Geen resultaten',
        inProgress: 'In afwachting',
        noOptionsAvailable: 'Geen opties beschikbaar',
        wrongPage: 'Deze pagina bestaat niet.',
        homeScreen: 'Ga naar de thuispagina!',
        selectAll: 'Alles selecteren',
        Filter: 'Filteren',
        ended: 'Afgerond',
        yourFav: 'Je favoriete teams',
        register: 'Opslaan',
        cancel: 'Annuleren',
        deleteSelection: 'Selectie verwijderen',
        addColumn: 'Kolom toevoegen',
        removeColumn: 'Kolom verwijderen',
        select: 'Selecteer uw keuze',
        selectMultiple: 'Selecteer uw keuzes',
        nothing: 'Niets',
        filterTeams: 'Teams filteren',
        filterLeagues: 'Competities filteren',
        filterMonths: 'Maanden filteren',
        findTeam: 'Zoek een team',
        leagueSurveilled: 'Weer te geven competitie(s)',
        score: 'Eindstand',
        favorites: 'FAVORIETEN',
        followLive: 'Volg live',
        scoreView: 'Scores weergeven',
        localizeArena: 'Arena lokaliseren',
        downloadICS: 'ICS-bestand',
        gameDetails: 'Spel details',
        events: 'Evenementen',
        final: 'Eind',
        standings: 'Standings',
        currentScore: 'Huidige score',
        showHidePreviousScores: 'Vorige scores tonen/verbergen',
        postponedGame: 'Spiel verschoben',
        signInWithGoogle: 'Iniciar sesión con Google',
        signOut: 'Uitloggen',
        authentication: 'Identificeer uzelf',
        continueWithEmail: 'Registreren / Inloggen',
        forgotPassword: 'Wachtwoord vergeten?',
        loggedInAs: 'Ingelogd als:',
        passwordResetSent: 'Er is een link voor het opnieuw instellen van je wachtwoord naar je e-mail verzonden!',
        incorrectPassword: 'Onjuist wachtwoord voor dit account. Probeer het opnieuw.',
        authError: 'Authentificatiefout: ',
        loginError: 'Inlogfout: ',
        enterEmailFirst: 'Voer eerst je e-mailadres in.',
        resetError: 'Resetfout: ',
        connectionError: 'Verbindingsfout: ',
        noUserLoggedIn: 'Geen gebruiker ingelogd.',
        confirmDeleteAccount:
          'Weet je zeker dat je je account permanent wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
        accountDeleted: 'Je account is succesvol verwijderd.',
        recentLoginRequired: 'Meld je uit veiligheidsoverwegingen af en opnieuw aan voordat je je account verwijdert.',
        deletionError: 'Verwijderfout: ',
        deleteAccount: 'Account verwijderen',
        emailPlaceholder: 'E-mailadres',
        passwordPlaceholder: 'Wachtwoord',
        signIn: 'Inloggen',
        signUp: 'Registreren',
        noAccount: 'Nog geen account?',
        alreadyHaveAccount: 'Heb je al een account?',
        passwordConfirmPlaceholder: 'Wachtwoord bevestigen',
        passwordsDoNotMatch: 'Wachtwoorden komen niet overeen.',
        userNotFound: 'Geen account gevonden voor dit e-mailadres.',
        emailAlreadyInUse: 'Dit e-mailadres is al in gebruik.',
        invalidCredentials: 'E-mail of wachtwoord onjuist.',
        or: 'of',
        profile: 'Mijn Profiel',
        changePreferences: 'Voorkeuren wijzigen',
      };
      break;
    case 'pt':
      translation = {
        all: 'TODOS',
        gamesOfDay: 'Jogos do dia',
        remainingGames: 'Jogos restantes',
        focusTeam: 'Siga um time',
        calendars: 'Agenda',
        connection: 'Conexão',
        noResults: 'Sem resultados',
        inProgress: 'Em andamento',
        noOptionsAvailable: 'Nenhuma opção disponível',
        wrongPage: 'Esta página não existe.',
        homeScreen: 'Ir para a página inicial!',
        selectAll: 'Selecionar tudo',
        Filter: 'Filtrar',
        ended: 'Encerrado',
        yourFav: 'Seus times favoritos',
        register: 'Salvar',
        cancel: 'Cancelar',
        deleteSelection: 'Excluir seleção',
        addColumn: 'Adicionar coluna',
        removeColumn: 'Remover coluna',
        select: 'Selecione sua opção',
        selectMultiple: 'Selecione suas opções',
        nothing: 'Nada',
        filterTeams: 'Filtrar times',
        filterLeagues: 'Filtrar ligas',
        filterMonths: 'Filtrar meses',
        findTeam: 'Encontrar um time',
        leagueSurveilled: 'Liga(s) a exibir',
        score: 'Placar final',
        favorites: 'FAVORITOS',
        followLive: 'Seguir ao vivo',
        scoreView: 'Mostrar placares',
        localizeArena: 'Localizar estádio',
        downloadICS: 'Arquivo .ics',
        gameDetails: 'Detalhes do jogo',
        events: 'Eventos',
        final: 'Final',
        standings: 'Classificação',
        currentScore: 'Placar atual',
        showHidePreviousScores: 'Mostrar/Ocultar placar anterior',
        postponedGame: 'Jogo adiado',
        signInWithGoogle: 'Iniciar sesión con Google',
        signOut: 'Sair',
        authentication: 'Identifique-se',
        continueWithEmail: 'Inscreva-se / Entrar',
        forgotPassword: 'Esqueceu a senha?',
        loggedInAs: 'Conectado como:',
        passwordResetSent: 'Um link de redefinição de senha foi enviado para o seu e-mail!',
        incorrectPassword: 'Senha incorrecta para esta conta. Por favor, tente novamente.',
        authError: 'Erro de autenticação: ',
        loginError: 'Erro de login: ',
        enterEmailFirst: 'Por favor, insira seu e-mail primeiro.',
        resetError: 'Erro de redefinição: ',
        connectionError: 'Erro de conexão: ',
        noUserLoggedIn: 'Nenhum usuário conectado.',
        confirmDeleteAccount:
          'Tem certeza de que deseja excluir permanentemente sua conta? Esta ação não pode ser desfeita.',
        accountDeleted: 'Sua conta foi excluída com sucesso.',
        recentLoginRequired: 'Por motivos de segurança, saia e entre novamente antes de excluir sua conta.',
        deletionError: 'Erro de exclusão: ',
        deleteAccount: 'Excluir conta',
        emailPlaceholder: 'E-mail',
        passwordPlaceholder: 'Senha',
        signIn: 'Entrar',
        signUp: 'Inscreva-se',
        noAccount: 'Não tem uma conta?',
        alreadyHaveAccount: 'Já tem uma conta?',
        passwordConfirmPlaceholder: 'Confirmar senha',
        passwordsDoNotMatch: 'As senhas não coincidem.',
        userNotFound: 'Conta não encontrada.',
        emailAlreadyInUse: 'Este e-mail já está em uso.',
        invalidCredentials: 'E-mail ou senha incorretos.',
        or: 'ou',
        profile: 'Meu Perfil',
        changePreferences: 'Alterar preferências',
      };
      break;
    case 'ru':
      translation = {
        all: 'ВСЕ',
        gamesOfDay: 'Игры дня',
        remainingGames: 'Оставшиеся игры',
        focusTeam: 'Следить за командой',
        calendars: 'Агенда',
        connection: 'Подключение',
        noResults: 'Нет результатов',
        inProgress: 'В процессе',
        noOptionsAvailable: 'Нет доступных вариантов',
        wrongPage: 'Эта страница не существует.',
        homeScreen: 'Перейти на главную страницу!',
        selectAll: 'Выбрать все',
        Filter: 'Фильтровать',
        ended: 'Завершено',
        yourFav: 'Ваши любимые команды',
        register: 'Сохранить',
        cancel: 'Отмена',
        deleteSelection: 'Удалить выделение',
        addColumn: 'Добавить столбец',
        removeColumn: 'Удалить столбец',
        select: 'Выберите свой вариант',
        selectMultiple: 'Выберите несколько вариантов',
        nothing: 'Ничего',
        filterTeams: 'Фильтровать команды',
        filterLeagues: 'Фильтровать лиги',
        filterMonths: 'Фильтровать месяцы',
        findTeam: 'Найти команду',
        leagueSurveilled: 'Лиги для отображения',
        score: 'Итоговый счет',
        favorites: 'ИЗБРАННОЕ',
        followLive: 'Следить в прямом эфире',
        scoreView: 'Показать результаты',
        localizeArena: 'Локализовать стадион',
        downloadICS: 'Файл .ics',
        gameDetails: 'Детали игры',
        events: 'События',
        final: 'Финал',
        standings: 'Таблица',
        currentScore: 'Текущий счет',
        showHidePreviousScores: 'Показать/скрыть предыдущие счета',
        postponedGame: 'Игра отложена',
        signInWithGoogle: 'Войти с помощью Google',
        signOut: 'Выйти',
        authentication: 'Идентифицируйте себя',
        continueWithEmail: 'Зарегистрироваться / Войти',
        forgotPassword: 'Забыли пароль?',
        loggedInAs: 'Вы вошли как:',
        passwordResetSent: 'Ссылка для сброса пароля была отправлена на вашу электронную почту!',
        incorrectPassword: 'Неверный пароль для этой учетной записи. Пожалуйста, попробуйте еще раз.',
        authError: 'Ошибка аутентификации: ',
        loginError: 'Ошибка входа: ',
        enterEmailFirst: 'Пожалуйста, сначала введите свой адрес электронной почты.',
        resetError: 'Ошибка сброса: ',
        connectionError: 'Ошибка подключения: ',
        noUserLoggedIn: 'Нет вошедших пользователей.',
        confirmDeleteAccount: 'Вы уверены, что хотите навсегда удалить свой аккаунт? Это действие нельзя отменить.',
        accountDeleted: 'Ваш аккаунт был успешно удален.',
        recentLoginRequired:
          'В целях безопасности, пожалуйста, выйдите из системы и войдите снова перед удалением аккаунта.',
        deletionError: 'Ошибка удаления: ',
        deleteAccount: 'Удалить аккаунт',
        emailPlaceholder: 'Электронная почта',
        passwordPlaceholder: 'Пароль',
        signIn: 'Войти',
        signUp: 'Зарегистрироваться',
        noAccount: 'Нет аккаунта?',
        alreadyHaveAccount: 'Уже есть аккаунт?',
        passwordConfirmPlaceholder: 'Подтвердите пароль',
        passwordsDoNotMatch: 'Пароли не совпадают.',
        userNotFound: 'Аккаунт не найден.',
        emailAlreadyInUse: 'Этот email уже используется.',
        invalidCredentials: 'Неверный email или пароль.',
        or: 'или',
        profile: 'Мой профиль',
        changePreferences: 'Изменить настройки',
      };
      break;
    case 'zh':
      translation = {
        all: '所有',
        gamesOfDay: '当天的比赛',
        remainingGames: '剩余比赛',
        focusTeam: '关注一个团队',
        calendars: '议程',
        connection: '连接',
        noResults: '没有结果',
        inProgress: '进行中',
        noOptionsAvailable: '没有可用选项',
        wrongPage: '此页面不存在。',
        homeScreen: '前往首页！',
        selectAll: '全选',
        Filter: '筛选',
        ended: '已结束',
        yourFav: '你最喜欢的球队',
        register: '保存',
        cancel: '取消',
        deleteSelection: '删除选择',
        addColumn: '添加列',
        removeColumn: '删除列',
        select: '选择你的选择',
        selectMultiple: '选择多个选项',
        nothing: '无',
        filterTeams: '筛选球队',
        filterLeagues: '筛选联赛',
        filterMonths: '筛选月份',
        findTeam: '查找球队',
        leagueSurveilled: '要显示的联赛',
        score: '最终得分',
        favorites: '收藏',
        followLive: '关注直播',
        scoreView: '显示比分',
        localizeArena: '本地化球馆',
        downloadICS: 'ICS文件',
        gameDetails: '比赛详情',
        events: '事件',
        final: '最终',
        standings: '排名',
        currentScore: '当前得分',
        showHidePreviousScores: '显示/隐藏之前的比分',
        postponedGame: '比赛推迟',
        signInWithGoogle: '使用Google登录',
        signOut: '退出登录',
        authentication: '身份验证',
        continueWithEmail: '注册 / 登录',
        forgotPassword: '忘记密码？',
        loggedInAs: '登录身份：',
        passwordResetSent: '重置密码链接已发送到您的邮箱！',
        incorrectPassword: '此帐户的密码不正确。请重试。',
        authError: '身份验证错误：',
        loginError: '登录错误：',
        enterEmailFirst: '请先输入您的电子邮件地址。',
        resetError: '重置错误：',
        connectionError: '连接错误：',
        noUserLoggedIn: '当前没有用户登录。',
        confirmDeleteAccount: '您确定要永久删除您的帐户吗？此操作无法撤销。',
        accountDeleted: '您的帐户已成功删除。',
        recentLoginRequired: '为了安全起见，请在删除帐户之前先退出并重新登录。',
        deletionError: '删除错误：',
        deleteAccount: '删除帐户',
        emailPlaceholder: '电子邮件地址',
        passwordPlaceholder: '密码',
        signIn: '登录',
        signUp: '注册',
        noAccount: '还没有账号？',
        alreadyHaveAccount: '已经有账号？',
        passwordConfirmPlaceholder: '确认密码',
        passwordsDoNotMatch: '密码不匹配。',
        userNotFound: '找不到帐户。',
        emailAlreadyInUse: '此电子邮件已被使用。',
        invalidCredentials: '电子邮件或密码错误。',
        or: '或',
        profile: '我的资料',
        changePreferences: '更改偏好',
      };
      break;
    default:
      translation = {
        all: 'ALL',
        gamesOfDay: 'Games of the day',
        remainingGames: 'Remaining games',
        focusTeam: 'Follow a team',
        calendars: 'Agenda',
        connection: 'Connection',
        noResults: 'No results',
        inProgress: 'In progress',
        noOptionsAvailable: 'No options available',
        wrongPage: "This screen doesn't exist.",
        homeScreen: 'Go to home screen!',
        selectAll: 'Select All',
        Filter: 'Filter',
        ended: 'Ended',
        yourFav: 'Your favorite teams',
        register: 'Save',
        cancel: 'Cancel',
        deleteSelection: 'Delete Selection',
        addColumn: 'Add Column',
        removeColumn: 'Remove Column',
        select: 'Select your choice',
        selectMultiple: 'Select your choices',
        nothing: 'Nothing',
        filterTeams: 'Filter teams',
        filterLeagues: 'Filter leagues',
        filterMonths: 'Filter months',
        findTeam: 'Find a Team',
        leagueSurveilled: 'League(s) to display',
        score: 'Final Score',
        favorites: 'FAVORITES',
        followLive: 'Follow Live',
        scoreView: 'Show scores',
        localizeArena: 'Localize Arena',
        downloadICS: 'ICS File',
        gameDetails: 'Game Details',
        events: 'Events',
        final: 'Final',
        standings: 'Standings',
        currentScore: 'Current Score',
        showHidePreviousScores: 'Show/Hide Previous Scores',
        postponedGame: 'Postponed Game',
        signInWithGoogle: 'Sign in with Google',
        signOut: 'Sign out',
        authentication: 'Please sign in',
        continueWithEmail: 'Sign up / Sign in',
        forgotPassword: 'Forgot Password?',
        loggedInAs: 'Logged in as:',
        passwordResetSent: 'A password reset link has been sent to your email inbox!',
        incorrectPassword: 'Incorrect password for this account. Please try again.',
        authError: 'Authentication error: ',
        loginError: 'Login error: ',
        enterEmailFirst: 'Please enter your email address first.',
        resetError: 'Reset error: ',
        connectionError: 'Connection error: ',
        noUserLoggedIn: 'No user currently logged in.',
        confirmDeleteAccount: 'Are you sure you want to delete your account? This cannot be undone.',
        accountDeleted: 'Account successfully deleted.',
        recentLoginRequired: 'Please log out and back in before deleting your account.',
        deletionError: 'Deletion error: ',
        deleteAccount: 'Delete Account',
        emailPlaceholder: 'Email Address',
        passwordPlaceholder: 'Password',
        signIn: 'Sign In',
        signUp: 'Sign Up',
        noAccount: 'No account yet?',
        alreadyHaveAccount: 'Already have an account?',
        passwordConfirmPlaceholder: 'Confirm Password',
        passwordsDoNotMatch: 'Passwords do not match.',
        userNotFound: 'No account found for this email.',
        emailAlreadyInUse: 'This email is already in use.',
        invalidCredentials: 'Incorrect email or password.',
        or: 'or',
        profile: 'My Profile',
        changePreferences: 'Change my preferences',
      };
      break;
  }
  return translation[word] ?? '';
};
